version: '3'

services:
  centrifugo:
    container_name: centri 
    image: centrifugo/centrifugo:latest
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
