version: '3'

services:
  centrifugo:
    container_name: centri 
    image: centrifugo/centrifugo:latest
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9090:9090
        restart: always
        mem_limit: 1GB
        cpus: 0.5

  grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes: 
            - ./grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=false
            - GF_AUTH_ANONYMOUS_ENABLED=false
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - 4000:3000

        mem_limit: 1GB
        cpus: 0.5
